"use client";

// ============================================================
// PathADraftBanner
// ------------------------------------------------------------
// Non-dismissible banner shown above the Path A (LLM-generated)
// result view. Makes it explicit to the user that the graph was
// produced from an LLM's training prior, not verified data, and
// must be reviewed before any output is trusted.
//
// Intentionally has no dismiss control and no state.
// ============================================================

interface PathADraftBannerProps {
  className?: string;
}

export function PathADraftBanner({ className = "" }: PathADraftBannerProps) {
  return (
    <div
      role="alert"
      className={`rounded-md border-l-4 border-amber-500 bg-amber-100 px-3 py-2 text-xs text-amber-900 ${className}`}
    >
      <p className="leading-5">
        <span className="font-semibold">Draft model.</span>{" "}
        This graph was generated by an LLM. The numbers reflect the LLM&apos;s
        training prior, not verified data. Review each node and edit before
        trusting any output.
      </p>
    </div>
  );
}

export default PathADraftBanner;
