/**
 * Type definitions for Forecast Mode (R6-05 / R6-06).
 *
 * Mirrors the EnsemblePrediction shape returned by the Python ensemble
 * sidecar (services/ensemble) and re-exported from
 * `lib/services/ensemble-client.ts`. Re-exporting here keeps Forecast-Mode
 * UI components decoupled from the HTTP-client module: components import
 * only from `@/lib/forecast/types`, the API route imports the client.
 *
 * The shape on the wire is `snake_case` because it is generated by the
 * Python Pydantic model. We deliberately keep snake_case in TypeScript so
 * the JSON payload round-trips without an extra transform step.
 */

export type ForecastHorizon = 1 | 2 | 3;

/** Mirror of services/ensemble/app.py::EnsemblePredictionResponse. */
export interface ForecastPrediction {
  column: string;
  prediction: number;
  lower_95: number;
  upper_95: number;
  /** Map of base-model name -> SLSQP optimiser weight in [0, 1]. Sum ~= 1. */
  model_weights: Record<string, number>;
  /** Map of base-model name -> the individual point prediction that model produced. */
  individual_predictions: Record<string, number>;
  /** AR(1)-detector classification, e.g. "stable", "trending", "volatile". */
  regime_type: string;
  /** AR(1) coefficient rho in [-1, 1]; informs the regime label. */
  rho: number;
  /** Upstream ensemble mode ("production", "research", ...). */
  mode: string;
  /**
   * R6-06: whether the SLSQP weights for this prediction were re-optimised
   * against EMA-derived Beta priors before predicting. Absent on responses
   * from older sidecar versions; treat undefined as false.
   */
  priors_applied?: boolean;
  /**
   * R6-06: number of /outcome calls accumulated for this column on the
   * sidecar. Used by the UI's "Learning active" indicator. Absent on
   * responses from older sidecar versions.
   */
  observation_count?: number;
}

/**
 * Payload accepted by POST /api/forecast.
 */
export interface ForecastRequest {
  csv: string;
  dateColumn: string;
  targetColumn: string;
  horizon: ForecastHorizon;
}

/**
 * Response returned by POST /api/forecast.
 *
 * `forecastId` is a server-generated opaque string the client should keep
 * if the user wants to later attach a calibration outcome to this
 * forecast (R6-06 uses this id to thread outcomes back into the ensemble
 * sidecar's EMA learner).
 */
export interface ForecastResponse {
  forecast: ForecastPrediction;
  forecastId: string;
  trainedAt: string;
  slsqpWeights: Record<string, number>;
  trainingSeconds: number;
  /** Number of rows used by the sidecar after date coercion. */
  rowCount: number;
}

/** Human-readable description of the AR(1)-detector regime label. */
export function describeRegime(regimeType: string): string {
  const key = regimeType.toLowerCase().trim();
  switch (key) {
    case "stable":
      return "Low autocorrelation; recent values do not drift in one direction.";
    case "trending":
    case "trend":
      return "High positive autocorrelation; the series is drifting in a consistent direction.";
    case "mean_reverting":
    case "mean-reverting":
      return "Negative autocorrelation; swings tend to revert toward the mean.";
    case "volatile":
      return "High variance relative to the autocorrelation; noisier than typical.";
    default:
      return `Regime label '${regimeType}' (see AR(1) coefficient rho for detail).`;
  }
}
